### PR TITLE
chore(ci): exprimental lualint integration

### PR DESCRIPTION
**Pull request by pluveto**
We have developed a tool called Lualint, which checks for basic formatting errors in user-submitted code, thereby reducing the workload of reviewers.

KAG-1186

### CODE REVIEW

**Comment by chronolaw** [comment]
We should add at least one line description for PR, it will be friendly to the reviewer.

**Comment by pluveto** [comment]
Seems we need to ask @wheelerlaw for helping us generate `kong_gh_app_id` `kong_gh_app_private_key` for each repo that uses private action.

**Comment by pluveto** [comment]
Looks good

image

**Review by chronolaw — APPROVED** [review]

**Comment by pluveto** [comment]
Can you merge this?

**Pull request closed without merging**
